# Generated by Django 4.2.13 on 2024-06-20 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_rename_attendance_attendanceentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseTA',
            new_name='TACourse',
        ),
        migrations.AlterField(
            model_name='attendanceentry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
