# Generated by Django 4.2.13 on 2024-07-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_toiletentry_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
        migrations.DeleteModel(
            name='StudentPicture',
        ),
    ]
