# Generated by Django 4.2.13 on 2024-07-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_student_picture_delete_studentpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceentry',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='attendance'),
        ),
    ]
